prep-html-skeleton - Mohammed Ikram
mohammed-ikram/prep-0222-code-solutions pull request #2
Opened 2022-02-19 21:34 UTC by mohammed-ikram

<img width="769" alt="Screen Shot 2022-02-19 at 1 24 41 PM" src="https://user-images.githubusercontent.com/99572164/154819840-9e4f1bcf-3f76-4b43-a09e-100c01f3024c.png">

2022-02-20 17:29 UTC, thebearingedge requested changes

2022-02-20 17:29 UTC, thebearingedge commented on prep-html-skeleton/index.html
> +    <title>HTML Skeleton Exercise</title>
Hi Mohammed, be sure to put a closing `</head>` tag before your opening `<body>` tag.

2022-02-22 07:11 UTC, mohammed-ikram commented
<img width="497" alt="Screen Shot 2022-02-21 at 11 09 38 PM" src="https://user-images.githubusercontent.com/99572164/155080750-c74a2692-7dcd-492a-8326-126e134bbc88.png">

2022-02-22 15:07 UTC, thebearingedge approved these changes

2022-03-02 03:01 UTC, merged