prep-html-syntax - Mohammed Ikram
mohammed-ikram/prep-0222-code-solutions pull request #3
Opened 2022-02-19 22:09 UTC by mohammed-ikram

<img width="799" alt="Screen Shot 2022-02-19 at 2 03 44 PM" src="https://user-images.githubusercontent.com/99572164/154820743-2363e281-5430-48de-b0fa-d14c083d6304.png">

2022-02-20 17:39 UTC, thebearingedge requested changes

2022-02-20 17:39 UTC, thebearingedge commented on prep-html-syntax/index.html
> +  <title>HTML Syntax</title>
Hi Mohammed, be sure to put your title within a `<head></head>` element.

2022-02-20 17:39 UTC, thebearingedge commented on prep-html-syntax/index.html
> +</html>
You have an extra closing `</html>` tag.

2022-02-22 07:23 UTC, mohammed-ikram commented
<img width="749" alt="Screen Shot 2022-02-21 at 11 22 07 PM" src="https://user-images.githubusercontent.com/99572164/155082409-c3fa4f17-77e4-4bfe-b9c8-73e9c2b2ac71.png">

2022-03-05 20:53 UTC, merged